### ISSUE TITLE
Preload context error: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by beniance** [iotaledger/firefly#1087]
## Issue description

Error type : Preload Context Error - Cannot read property 'id' of undefined 

## Wallet version

Firefly Version: 1.1.0

## System specification

Windows 10 x64

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

1.Open Firefly 
2. Enter de PIN and ok
3. Error and only profile without my migration wallet ( 0 Mi ) 

App Version: 1.1.0

platform: win32
platformVersion: 10.0.19042
platformArchitecture: x64
cpuCount: 4
totalMem: 5989.4 MB
freeMem: 3768.0 MB
userPath: C:\Users\USER \AppData\Roaming\Firefly

Error Type: Preload Context Error

Error: Uncaught TypeError: Cannot read property 'id' of undefined
    at C:\Users\USER\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:165586
    at C:\Users\USER\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:197606
    at Array.forEach (<anonymous>)
    at destroy (C:\UsersUSER\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:197594)
    at C:\Users\USER\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:191379

**Comment by crosario79** [comment]
After migrating my tokens from the Trinity wallet today, I'm also getting the same "Preload Context Error" message.  My account is showing a balance of 0 Mi.  Any advice on how to resolve this issue will be greatly appreciated.

**Comment by beniance** [comment]
I have the same issue :+1:

**Comment by rajivshah3** [comment]
> My account is showing a balance of 0 Mi

@crosario79 is your balance is showing as 0 in Trinity or in Firefly?

**Comment by crosario79** [comment]
@rajivshah3 my balance is 0 in both the Trinity and Firefly wallets.  Prior to confirming the migration to Firefly, I did confirm the amount that was to be transferred from Trinity.  I just logged in again to my Firefly wallet and noticed that under status, it says "Network Disconnected"

**Comment by beniance** [comment]
He creado un nuevo perfil, sin desinstalar firefly ni borrar el otro perfil y he importado la seed
Ya tengo mi cartera asociada al nuevo perfil con todos los Iotas

**Comment by crosario79** [comment]
@beniance Muchas gracias por la recomendación. Creé otro perfil sin borrar el otro perfil e importé la seed. Mi cartera ahora está conectada al nuevo perfil con todos los Iotas.

**Comment by Alex71189** [comment]
I have exactly the same problem. After migration i see everything working and my balance was correct. Then i closed and start again Firefly and get the error 

App Version: 1.1.0

platform: win32
platformVersion: 10.0.18363
platformArchitecture: x64
cpuCount: 4
totalMem: 12271.1 MB
freeMem: 9190.1 MB
userPath: C:\Users\Alex\AppData\Roaming\Firefly

Error Type: Preload Context Error

Error: Uncaught TypeError: Cannot read property 'id' of undefined
    at C:\Users\Alex\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:165586
    at C:\Users\Alex\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:197606
    at Array.forEach (<anonymous>)
    at destroy (C:\Users\Alex\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:197594)
    at C:\Users\Alex\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:191379

I translate the workaround from crosario and beniance and now it is working. Thank you.

**Comment by ms17341** [comment]
I am having this same issue. Error pops up and shows not connected. Only happens to one of my profiles.

**Comment by Nikitaman92** [comment]
I have the same error message in my wallet.

**Comment by Hugin64** [comment]
I have the same issue. Firefly worked perfectly fine for me, but after I changed my Pin I have the error message and the 0 iota wallet.

**Comment by thiagomen001** [comment]
same issue

**Comment by bear2234** [comment]
same issue was working great for about a day full balance easy migration, then error message and balance reads 0mi

**Comment by cztsp** [comment]
i have the same issue.
After the succesful migration I had my balance correctly, closed the app, opened it a day after again and the error appeared.

**Comment by Stoyvo** [comment]
Funds are locked. Wallet is non-functional, this issue should be P0 and fixed immediately.

Please resolve this issue, it's unfair to lock funds in a non-functional wallet.

**Comment by Phyloiota** [comment]
Here are the links to the  2 part-guide:
https://phyloiota.medium.com/iota-hornet-node-installation-81747de28338
https://phyloiota.medium.com/iota-hornet-node-installation-2-8f2639e04d1d

**Comment by cztsp** [comment]
does anybody recognized any improvement?

**Comment by sagelev** [comment]
I have the same problem. Who is responsible? Who can solve this problem?

**Comment by Phyloiota** [comment]
This seems to work out for most windows users that have this problem as described in this thread:
Have a backup of your 24 Seed words safely stored!!!
Uninstall the Firefly App from your system.
As a standard uninstall still leaves the folder with the application data on your system, which could cause this error,
after you have deleted the app search for this folder: `[your username]/Appdata/Roaming/Firefly`    and delete this folder.
Then do an install with a freshly downloaded Firefly version and restore the wallet with the 24 seed words... use a different pin code than before (though i don't think it's related to that)... i hope this may help for most of you here

**Comment by Sha13332** [comment]
I  have the same problem, but I use mac os should I do the same?

**Comment by sagelev** [comment]
It worked at me! I'm really happy !

**Comment by Phyloiota** [comment]
> I have the same problem, but I use mac os should I do the same?

I am not 100% sure if it will also help on mac, but try it. Make really sure that you have backups of 24 words and stronghold file.
the folder for Mac to delete is this one:
`Mac: ~/Library/Application Support/Firefly `

**Comment by cztsp** [comment]
> 
> 
> This seems to work out for most windows users that have this problem as described in this thread:
> Have a backup of your 24 Seed words safely stored!!!
> Uninstall the Firefly App from your system.
> As a standard uninstall still leaves the folder with the application data on your system, which could cause this error,
> after you have deleted the app search for this folder: `[your username]/Appdata/Roaming/Firefly` and delete this folder.
> Then do an install with a freshly downloaded Firefly version and restore the wallet with the 24 seed words... use a different pin code than before (though i don't think it's related to that)... i hope this may help for most of you here

that sworked well in my case (win 10). thanks

**Comment by Tuditi** [comment]
Do you guys still experience the error in 1.6.5. If not, I'll close this issue.

**Comment by begonaalvarezd** [comment]
Closing issue due to inactivity, please upgrade to the latest app version and reopen the issue if the problem persists 🌷
