### ISSUE TITLE
Error on wallet Close

### ISSUE THREAD

**Issue by alegroSandermann** [iotaledger/firefly#1095]
## Issue description

Have 4 profiles in firefly. two are identical. Want to switch profile so i logged out of a profile. after some seconds i got the following error

## Wallet version

1.1.0

## System specification

What is your operating system?

windows

## Is it a repeatable issue?

N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. logged into profile 1 and copied a address to receive iota
2. logged out of profile 1
3. the error occurs

## Expected behaviour

log out of profil 1 to login into profile 2

## Actual behaviour

error occurs but firefly stays open

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.App Version: 1.1.0

platform: win32
platformVersion: 10.0.19042
platformArchitecture: x64
cpuCount: 16
totalMem: 65454.7 MB
freeMem: 56584.0 MB
userPath: C:\Users\sande\AppData\Roaming\Firefly

Error Type: Preload Context Error

Error: Uncaught TypeError: Cannot read property 'migratedTransactions' of undefined
    at C:\Users\sande\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:165586
    at C:\Users\sande\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:197606
    at Array.forEach (<anonymous>)
    at destroy (C:\Users\sande\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:197594)
    at C:\Users\sande\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:191379

**Comment by Xantus-78** [comment]
Same Problem. Created profile (without creating a wallet). Shut the computer down. Next day following message:

App Version: 1.1.0

platform: macOS
platformVersion: 11
platformArchitecture: x64
cpuCount: 4
totalMem: 8192.0 MB
freeMem: 26.4 MB
userPath: /Users/Username/Library/Application Support/Firefly

Error Type: Preload Context Error

Error: Uncaught TypeError: Cannot read property 'id' of undefined
    at /private/var/folders/g0/nvv7nsp13hn8zgdllz9682x00000gp/T/AppTranslocation/F5991308-AF53-4F81-B941-DDE1644020B5/d/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:165586
    at /private/var/folders/g0/nvv7nsp13hn8zgdllz9682x00000gp/T/AppTranslocation/F5991308-AF53-4F81-B941-DDE1644020B5/d/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:197606
    at Array.forEach (<anonymous>)
    at destroy (/private/var/folders/g0/nvv7nsp13hn8zgdllz9682x00000gp/T/AppTranslocation/F5991308-AF53-4F81-B941-DDE1644020B5/d/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:197594)
    at /private/var/folders/g0/nvv7nsp13hn8zgdllz9682x00000gp/T/AppTranslocation/F5991308-AF53-4F81-B941-DDE1644020B5/d/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:191379






It is not possible to delete this buggy profile, while I still am able to create and delete other profiles without any problem.

**Comment by begonaalvarezd** [comment]
Closing issue due to inactivity, please upgrade to the latest app version and reopen the issue if the problem persists 🌷
