### ISSUE TITLE
Error Type: Preload Context Error

### ISSUE THREAD

**Issue by therealBlackFlag** [iotaledger/firefly#1114]
## Issue description

Error comes within 1 minute without doing anything. 
wallet needs to closed, cant do anything else

## Wallet version

1.1.0

## System specification

WIN10 64Bit newest version

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. just login and wait
2.
3.

## Expected behaviour

no error

## Actual behaviour

error after around 1 minute

## Errors

App Version: 1.1.0

platform: win32
platformVersion: 10.0.19042
platformArchitecture: x64
cpuCount: 8
totalMem: 32730.6 MB
freeMem: 24740.6 MB
userPath: C:\Users\XXX\AppData\Roaming\Firefly

Error Type: Preload Context Error

TypeError: Cannot read property 'isValid' of undefined
    at w.performValidation (C:\Users\XXX\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:159429)
    at C:\Users\XXX\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:165421
    at C:\Users\XXX\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:197606
    at Array.forEach (<anonymous>)
    at destroy (C:\Users\XXX\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:197594)
    at C:\Users\XXX\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:191379

**Comment by MiKeF05** [comment]
@therealBlackFlag Were you able to solve your issue with the latest version of Firefly?

**Comment by begonaalvarezd** [comment]
Closing issue due to inactivity, please upgrade to the latest app version and reopen the issue if the problem persists 🌷
