### ISSUE TITLE
M1 Capability

### ISSUE THREAD

**Issue by ingokpp** [iotaledger/firefly#1225]
## Issue description

Currently the repository dependencies like electron (arm based) won't work if you're using a Mac with a m1 processor. I would love to fix all the dependencies errors so that the Desktop / iOs will build successfully.

## Wallet version

Which version of wallet are you using?

- develop branch

## System specification

Macbook Air - macOs Big Sur v11.3.1 - Apple M1 Chip

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Just try to setup the repository using an M1 Device. 
`yarn`

## Expected behaviour

Install all dependencies and setup the project.

## Actual behaviour

Dependencie errors...

## Errors

`[4/4] 🔨  Building fresh packages...
[1/2] ⡀ wallet-nodejs-binding
error /Users/ingokopp/Documents/Workspace/firefly/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/ingokopp/Documents/Workspace/firefly/node_modules/electron
Output:
HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v9.4.4/electron-v9.4.4-darwin-arm64.zip
    at EventEmitter.<anonymous> (/Users/ingokopp/Documents/Workspace/firefly/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (events.js:376:20)
    at module.exports (/Users/ingokopp/Documents/Workspace/firefly/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/Users/ingokopp/Documents/Workspace/firefly/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:483:26)
    at ClientRequest.emit (events.js:388:22)
    at ClientRequest.origin.emit (/Users/ingokopp/Documents/Workspace/firefly/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
`

**Comment by ingokpp** [comment]
I've created a [branch](https://github.com/ingokpp/firefly/tree/m1) to fix this issue.
It's ok if you think this fix is unnecessary.  I just want to make it work for me so i can contribute more stuff :)

**Comment by PatrickHuetter** [comment]
+1

**Comment by begonaalvarezd** [comment]
Closing issue due to inactivity, please upgrade to the latest app version and reopen the issue if the problem persists 🌷
