### ISSUE TITLE
[Ledger migration] Index 11 after confirming first Transaction: "Error: Uncaught TypeError: Cannot read property 'inputs' of undefined"

### ISSUE THREAD

**Issue by Metz-2** [iotaledger/firefly#1309]
## Issue description

While doing migration test (Index 11) "scenario: Funds spread across many spent addresses with each >=1Mi". 
Used 2 x "check again" to see correct balance then rerun bundle mining twice (change 3/5 to 2/5 for some addresses)
Confirming first Transaction on Ledger worked. Window for second transaction pops up and Firefly shows error:

```
 App Version: 1.1.0
 
 platform: linux
 platformVersion: 5.11.22-2-MANJARO
 platformArchitecture: x64
 cpuCount: 16
 totalMem: 15948.1 MB
 freeMem: 390.0 MB
 userPath: /home/metz/.config/Firefly
 
 Error Type: Preload Context Error
 
 Error: Uncaught TypeError: Cannot read property 'inputs' of undefined
     at /tmp/.mount_firefljiXiEk/resources/app.asar/public/build/preload.js:43689:13
     at /tmp/.mount_firefljiXiEk/resources/app.asar/public/build/preload.js:46327:9038
     at Array.forEach (<anonymous>)
     at destroy (/tmp/.mount_firefljiXiEk/resources/app.asar/public/build/preload.js:46327:9026)
     at /tmp/.mount_firefljiXiEk/resources/app.asar/public/build/preload.js:46327:1250
```

Migration gets stuck at this point but first transaction still went through.

---
Update:
I can confirm that this error is reproducible following the same steps again. 
What caught my eye is the output in the error log

```
totalMem: 15948.1 MB
freeMem: 379.2 MB
```
Which differs greatly from the actual free memory (displayed at htop). There it is ~8000 MB free.
Possible memory allocation problem?

---

Another try, same result.
```
App Version: 1.1.0

platform: linux
platformVersion: 5.11.22-2-MANJARO
platformArchitecture: x64
cpuCount: 16
totalMem: 15948.1 MB
freeMem: 329.7 MB
userPath: /home/metz/.config/Firefly

Error Type: Preload Context Error

Error: Uncaught TypeError: Cannot read property 'inputs' of undefined
    at /tmp/.mount_fireflIMBKxh/resources/app.asar/public/build/preload.js:43689:13
    at /tmp/.mount_fireflIMBKxh/resources/app.asar/public/build/preload.js:46327:9038
    at Array.forEach (<anonymous>)
    at destroy (/tmp/.mount_fireflIMBKxh/resources/app.asar/public/build/preload.js:46327:9026)
    at /tmp/.mount_fireflIMBKxh/resources/app.asar/public/build/preload.js:46327:1250
```
dev console
```
VM57 preload.js:46932 Error: Uncaught TypeError: Cannot read property 'inputs' of undefined
    at VM57 preload.js:43689
    at VM57 preload.js:46327
    at Array.forEach (<anonymous>)
    at destroy (VM57 preload.js:46327)
    at VM57 preload.js:46327
(anonymous) @ VM57 preload.js:46932
```

**Comment by MiKeF05** [comment]
I guess this issue can be closed
