### ISSUE TITLE
Firefly reports error during funds migration

### ISSUE THREAD

**Issue by phaussy78** [iotaledger/firefly#1408]
## Issue description
Firefly reports error during funds migration

## Wallet version
1.2.0

## System specification
MacOS 11.4

## Is it a repeatable issue?
Y

## Steps To reproduce the issue
All steps followed until being ask to migrate tokens
Clicked on Migrate tokens

## Expected behaviour
Would have expected token to have been migrated

## Actual behaviour
Error being displayed

## Errors

App Version: 1.2.0

platform: macOS
platformVersion: 11
platformArchitecture: x64
cpuCount: 8
totalMem: 16384.0 MB
freeMem: 2211.2 MB
userPath: /Users/<username>/Library/Application Support/Firefly

Error Type: Preload Context Error

Error: Uncaught TypeError: Cannot read property 'forEach' of null
    at /Applications/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:548089
    at /Applications/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:590377
    at Array.forEach (<anonymous>)
    at destroy (/Applications/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:590365)
    at /Applications/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:582435

**Comment by phaussy78** [comment]
After repeating the same steps several times, it appears that a single transaction gets transferred every single time. The transferred address in the Chrysalis mainnet displays the correct balance (checked in mainnet explorer). Manually creating the account in firefly allows the address (and correct balance) to be displayed (in Firefly). Looking at the Firefly original error, it simply looks like Firefly has an issue iterating an array of transactions (Error: Uncaught TypeError: Cannot read property 'forEach' of null). Or the array is not correctly constructed. Hope that helps a little....

**Comment by phaussy78** [comment]
Another finding that may help....

After manually creating the account in Firefly (previous comment), I repeated the original migration using the option to migrate a different index (even if I had only a single index). The original error (Error: Uncaught TypeError: Cannot read property 'forEach' of null) did not occur and transactions are being migrated. So it looks like the array object is dependent on the account creation...

**Comment by dsx5000** [comment]
Hello, I have the same issue with firefly version 1.3.0, did you find a solution?

**Comment by MiKeF05** [comment]
@dsx5000 Do you still have this issue?

**Comment by dsx5000** [comment]
Hello, 

it was possible to solve by installing firefly version 1.2.0.

Thank you!
