### ISSUE TITLE
Create a Wallet

### ISSUE THREAD

**Issue by hassping** [iotaledger/firefly#1440]
### Issue description

Error when creating a new wallet within an account

### Firefly version

App Version: 1.2.0

### OS details

Ubuntu 20.04.3

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Open an Account without wallets
2. Create a Wallet
3. Issue appears
...

### Expected behaviour

Create a new wallet

### Actual behaviour

Error Message

### Errors

App Version: 1.2.0

platform: linux
platformVersion: 5.11.0-27-generic
platformArchitecture: x64
cpuCount: 12
totalMem: 31827.4 MB
freeMem: 16434.8 MB
userPath: /home/hassping/.config/Firefly

Error Type: Render Context Error

TypeError: Cannot read property 'signerType' of undefined
    at a (file:///tmp/.mount_fireflcrgIzy/resources/app.asar/public/build/index.js:2:2911806)
    at file:///tmp/.mount_fireflcrgIzy/resources/app.asar/public/build/index.js:2:2912401
    at n (file:///tmp/.mount_fireflcrgIzy/resources/app.asar/public/build/index.js:2:2843814)
    at m (file:///tmp/.mount_fireflcrgIzy/resources/app.asar/public/build/index.js:2:2843984)
    at HTMLInputElement.<anonymous> (file:///tmp/.mount_fireflcrgIzy/resources/app.asar/public/build/index.js:2:2201023)

**Comment by MiKeF05** [comment]
Hello, do you use a ledger or a normal software wallet?

**Comment by begonaalvarezd** [comment]
Closing issue due to inactivity, please upgrade to the latest app version and reopen the issue if the problem persists 🌷
