### ISSUE TITLE
Unable to create a new wallet after migration from Trinity using Ledger nano-x

### ISSUE THREAD

**Issue by karlherman** [iotaledger/firefly#1494]
### Issue description

I migrated my wallet from trinity to firefly using ledger nano-x.
All went apparently well. The correct balance was displayed.
After closing and starting firefly again several times and changing the PIN.
Displayed balance is 0, no wallet is displayed.
My try to create a new account failed.
Receiving error message below in the Error section.

### Firefly version

1.2.0

### OS details

Windows 10, 10.0.19042

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. open firefly as admin
2. type PIN
3. firefly displays balance 0, which should be wrong
4. connecting lendger nano-x 
5. selecting IOTA account in ledger, answering "device connected"
6. firefly displays "hardware device is connected" is displayed
7. testing to create a new wallet
8. error message "Unfortunately an error has occurred in Firefly." See below in section Errors.
...

### Expected behaviour

I expected firefly to show my balance
and to create a wallet

### Actual behaviour

firefly doesnt show my balance
i am not able to create new wallet

### Errors

Error 1:
App Version: 1.2.0

platform: win32
platformVersion: 10.0.19042
platformArchitecture: x64
cpuCount: 4
totalMem: 8113.0 MB
freeMem: 4996.7 MB
userPath: C:\Users\AdminYoga\AppData\Roaming\Firefly

Error Type: Preload Context Error

Error: Uncaught TypeError: Cannot read property 'signerType' of undefined
    at C:\Users\AdminYoga\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:548089
    at C:\Users\AdminYoga\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:590377
    at Array.forEach (<anonymous>)
    at destroy (C:\Users\AdminYoga\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:590365)
    at C:\Users\AdminYoga\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:582435

Error 2:
Fri, 24 Sep 2021 23:24:02 GMT
ClientError: {}

Fri, 24 Sep 2021 23:23:23 GMT
ClientError: {}

Fri, 24 Sep 2021 23:21:21 GMT
ClientError: {}

**Comment by karlherman** [comment]
I was able to solve the problem by myself.
After creating a new profile the correct balance has been shown.
I am not able close this issue #1494, so please close this issue.
