### ISSUE TITLE
Cannot read property 'alias' of undefined

### ISSUE THREAD

**Issue by adertask** [iotaledger/firefly#1521]
### Issue description

Error on sending iota from one profile wallet to another in same Firefly app.

### Firefly version

1.2.0

### OS details

10.0.19043

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

I had six profiles with one wallet each.
Created a new profile with 6 wallets inside 
1) created new profile 'X'
2) send iota from old profile 1 existing profile 'X' wallet 1
3) created new wallet 2 inside new profile 'X'
4) go to old profile 2
5) send iota from old profile 2 existing profile 'X' wallet 2
and so on
with last old profile 6 I wanted to send iota and after pressing the button "send" I got this error.

Nethertheless iota were sent from profile 6 to profile 'X' wallet 6

### Expected behaviour

no error

### Actual behaviour

error

### Errors

App Version: 1.2.0

platform: win32
platformVersion: 10.0.19043
platformArchitecture: x64
cpuCount: 12
totalMem: 16228.7 MB
freeMem: 10398.1 MB
userPath: C:\Users\harni\AppData\Roaming\Firefly

Error Type: Preload Context Error

Error: Uncaught TypeError: Cannot read property 'alias' of undefined
    at C:\Users\harni\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:548089
    at C:\Users\harni\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:590377
    at Array.forEach (<anonymous>)
    at destroy (C:\Users\harni\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:590365)
    at C:\Users\harni\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:582435

**Comment by nicole-obrien** [comment]
Where there any ux issues with the names of the profiles or wallets? Did you have any profiles or wallets with identical names?

**Comment by adertask** [comment]
No.. no profiles with same names. Only what could be is... each profile had a "Wallet 1".
And in profile "X" I created "Wallet 1" to "Wallet 6".
And in this case I sent iota from "Profile 6" "Wallet 1" to new profile "XYZ" to "Wallet 6".

**Comment by nicole-obrien** [comment]
Thank you for reporting this error and the additional info. The team is currently looking at ways to improve error messages, so that we can better troubleshoot the likes of these issues. As your funds are safe and the functionality took place (transferring funds), this issue will remain low priority until we improve the error messages.

**Comment by begonaalvarezd** [comment]
Closing issue due to inactivity, please upgrade to the latest app version and reopen the issue if the problem persists 🌷
