### ISSUE TITLE
Cannot read property 'balance' of undefined

### ISSUE THREAD

**Issue by Javahake** [iotaledger/firefly#1822]
App Version: 1.2.0

platform: win32
platformVersion: 10.0.19042
platformArchitecture: x64
cpuCount: 12
totalMem: 16185.7 MB
freeMem: 10800.3 MB
userPath: C:\Users\noack\AppData\Roaming\Firefly

Error Type: Preload Context Error

Error: Uncaught TypeError: Cannot read property 'balance' of undefined
    at C:\Users\noack\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:548089
    at C:\Users\noack\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:590377
    at Array.forEach (<anonymous>)
    at destroy (C:\Users\noack\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:590365)
    at C:\Users\noack\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:582435

**Comment by Javahake** [comment]
bug has been fixed...firefly works again
