### ISSUE TITLE
Crash during wallet creation

### ISSUE THREAD

**Issue by myweirdname** [iotaledger/firefly#1840]
### Issue description

- Created new wallet under seed, and have sent iota to them.
- Next the transfer happened, but GUI was not yet updated showing the balance.
- Then I created another wallet, and then the crash happened

### Firefly version

1.3.0

### OS details

Windows

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

Not crash

### Actual behaviour

Crash

### Errors

App Version: 1.3.0

platform: win32
platformVersion: 10.0.19043
platformArchitecture: x64
cpuCount: 12
totalMem: 16333.2 MB
freeMem: 11505.8 MB

Error Type: Callback Error syncAccounts

TypeError: Cannot read property 'depositAddress' of undefined
    at file:///C:/Users/Family/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2112599
    at Array.map (<anonymous>)
    at Bs (file:///C:/Users/Family/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2112538)
    at onSuccess (file:///C:/Users/Family/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2110189)
    at Function.t.<computed>.<computed> (file:///C:/Users/Family/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2108070)

**Comment by joescharf** [comment]
Also received this error creating a new wallet, firefly v.1.3.2:

```
App Version: 1.3.2

platform: macOS
platformVersion: 12.1
platformArchitecture: x64
cpuCount: 8
totalMem: 16384.0 MB
freeMem: 45.6 MB

Error Type: Callback Error syncAccounts

TypeError: Cannot read property 'depositAddress' of undefined
    at file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2112661
    at Array.map (<anonymous>)
    at Bs (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2112600)
    at onSuccess (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2110251)
    at Function.t.<computed>.<computed> (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2108132)
```

**Comment by rajivshah3** [comment]
Hi @joescharf @myweirdname , are you using a Ledger device?

**Comment by joescharf** [comment]
> Hi @joescharf @myweirdname , are you using a Ledger device?

Yes I'm using a Ledger. It was able to create the wallet and everything seems to work fine as expected, but wanted to pass this error along

**Comment by myweirdname** [comment]
No leger device just basic firefly

**Comment by MiKeF05** [comment]
This should be fixed in the latest release
