### ISSUE TITLE
[Bug]: my app doesnt start and interrupted a transaction. Now funds didnt arrive and app doesnt start

### ISSUE THREAD

**Issue by barciada** [iotaledger/firefly#2133]
### Issue description

I was in a middle of a transaction and error ocurred. Now funds have not arrived and app doesnt start

### Expected behaviour

I could receive funds safely and stake them 

### Actual behaviour

Everything is stuck for 4 hours now

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

![Captura de pantalla 2022-01-15 144659error](https://user-images.githubusercontent.com/97793480/149626227-b572c05e-d844-4123-9dd4-d817fa56f676.jpg)

### Diagnostics

```shell
App Version: 1.3.2

platform: win32
platformVersion: 10.0.19043
platformArchitecture: x64
cpuCount: 2
totalMem: 3071.2 MB
freeMem: 1047.5 MB

Error Type: Callback Error latestAddress

TypeError: Cannot read property 'balance' of undefined
    at file:///C:/Users/Usuario/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:3060474
    at Array.map (<anonymous>)
    at file:///C:/Users/Usuario/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:3060411
    at Array.forEach (<anonymous>)
    at file:///C:/Users/Usuario/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:3060370
    at Array.forEach (<anonymous>)
    at file:///C:/Users/Usuario/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:3060339
    at file:///C:/Users/Usuario/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:3060502
    at m (file:///C:/Users/Usuario/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:2027894)
    at Array.<anonymous> (file:///C:/Users/Usuario/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:2027973)
    at i (file:///C:/Users/Usuario/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:2027509)
    at Object.update (file:///C:/Users/Usuario/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:2027565)
    at file:///C:/Users/Usuario/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:3062568
    at onSuccess (file:///C:/Users/Usuario/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:2114063)
    at Function.t.<computed>.<computed> (file:///C:/Users/Usuario/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:2108132)
```

### Errors

```shell
App Version: 1.3.2

platform: win32
platformVersion: 10.0.19043
platformArchitecture: x64
cpuCount: 2
totalMem: 3071.2 MB
freeMem: 1047.5 MB

Error Type: Callback Error latestAddress

TypeError: Cannot read property 'balance' of undefined
    at file:///C:/Users/Usuario/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:3060474
    at Array.map (<anonymous>)
    at file:///C:/Users/Usuario/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:3060411
    at Array.forEach (<anonymous>)
    at file:///C:/Users/Usuario/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:3060370
    at Array.forEach (<anonymous>)
    at file:///C:/Users/Usuario/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:3060339
    at file:///C:/Users/Usuario/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:3060502
    at m (file:///C:/Users/Usuario/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:2027894)
    at Array.<anonymous> (file:///C:/Users/Usuario/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:2027973)
    at i (file:///C:/Users/Usuario/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:2027509)
    at Object.update (file:///C:/Users/Usuario/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:2027565)
    at file:///C:/Users/Usuario/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:3062568
    at onSuccess (file:///C:/Users/Usuario/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:2114063)
    at Function.t.<computed>.<computed> (file:///C:/Users/Usuario/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:2108132)
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by asalihcelik** [comment]
exactly the same problem i have now i send some iota funds to my wallet now i cant reach my wallet it keeps loading after i type the pin,
what a disappointment

**Comment by asalihcelik** [comment]
- [ ] 
![firefly problem](https://user-images.githubusercontent.com/83776330/149626732-36fe2ced-6767-408d-a5b9-9805dd3d4f87.jpg)
this is how my app looks like

**Comment by MiKeF05** [comment]
Please have  look at the solution in #2131.

**Comment by asalihcelik** [comment]
still same problem should i also delete stronghold file ? im using windows 10

**Comment by barciada** [comment]
Right I think I sorted it. Opened a new profile in same Firefly (no uninstall, no new install). Then migrate my funds from ledger security copy and all was working except the staking. Doesnt accept new staking funds but at least I had access to the wallet.
Hope it works with you guys

**Comment by asalihcelik** [comment]
> Right I think I sorted it. Opened a new profile in same Firefly (no uninstall, no new install). Then migrate my funds from ledger security copy and all was working except the staking. Doesnt accept new staking funds but at least I had access to the wallet. Hope it works with you guys

just i did same exatly since i dont have ledger but i open new profile and save my wallet 24 word and then i was able to reach my wallet

**Comment by asalihcelik** [comment]
But As a early user and bug finder of this platform I hope iota might airdrop us in future :)

**Comment by MiKeF05** [comment]
This should be fixed with the latest release.
