### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by klassenbruder** [iotaledger/firefly#2147]
### Issue description

App Version: 1.3.2

platform: macOS
platformVersion: 11.6
platformArchitecture: x64
cpuCount: 8
totalMem: 16384.0 MB
freeMem: 908.1 MB

Error Type: Callback Error sendLedgerMigrationBundle

TypeError: Cannot read property 'forEach' of null
    at file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2122648
    at Array.forEach (<anonymous>)
    at file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2122615
    at onSuccess (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2122993)
    at Function.t.<computed>.<computed> (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2108132)

### Expected behaviour

App Version: 1.3.2

platform: macOS
platformVersion: 11.6
platformArchitecture: x64
cpuCount: 8
totalMem: 16384.0 MB
freeMem: 908.1 MB

Error Type: Callback Error sendLedgerMigrationBundle

TypeError: Cannot read property 'forEach' of null
    at file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2122648
    at Array.forEach (<anonymous>)
    at file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2122615
    at onSuccess (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2122993)
    at Function.t.<computed>.<computed> (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2108132)

### Actual behaviour

App Version: 1.3.2

platform: macOS
platformVersion: 11.6
platformArchitecture: x64
cpuCount: 8
totalMem: 16384.0 MB
freeMem: 908.1 MB

Error Type: Callback Error sendLedgerMigrationBundle

TypeError: Cannot read property 'forEach' of null
    at file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2122648
    at Array.forEach (<anonymous>)
    at file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2122615
    at onSuccess (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2122993)
    at Function.t.<computed>.<computed> (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2108132)

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Hello, when does this error appear? Could you share some more detail for the steps needed to reproduce this error?

**Comment by nicole-obrien** [comment]
Closing the issue as the form has been incorrectly filled in. Feel free to reopen an issue correctly.
