### ISSUE TITLE
[Bug]: Login to profile fails with: Callback Error latestAddress

### ISSUE THREAD

**Issue by ajbmachon** [iotaledger/firefly#2198]
### Issue description

When starting the wallet, after entering the code to unlock my profile an error happens.

### Expected behaviour

Login works.

### Actual behaviour

Empty screen with firefly logo in the middle.

### Can the issue reliably be reproduced?

No

### Errors

```shell
App Version: 1.3.2

platform: win32
platformVersion: 10.0.19044
platformArchitecture: x64
cpuCount: 16
totalMem: 32697.6 MB
freeMem: 22687.6 MB

Error Type: Callback Error latestAddress

TypeError: Cannot read property 'balance' of undefined
    at file:///C:/Users/Andre/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:3060474
    at Array.map (<anonymous>)
    at file:///C:/Users/Andre/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:3060411
    at Array.forEach (<anonymous>)
    at file:///C:/Users/Andre/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:3060370
    at Array.forEach (<anonymous>)
    at file:///C:/Users/Andre/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:3060339
    at file:///C:/Users/Andre/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:3060502
    at m (file:///C:/Users/Andre/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:2027894)
    at Array.<anonymous> (file:///C:/Users/Andre/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:2027973)
    at i (file:///C:/Users/Andre/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:2027509)
    at Object.update (file:///C:/Users/Andre/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:2027565)
    at file:///C:/Users/Andre/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:3062568
    at onSuccess (file:///C:/Users/Andre/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:2114063)
    at Function.t.<computed>.<computed> (file:///C:/Users/Andre/AppData/Local/Programs/desktop/Firefly/resources/app.asar/public/build/index.js:2:2108132)
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Hello, can you try to create a new profile and restore your wallet either with your 24 words or the stronghold file + password? If you use a ledger then you are able restore it with your ledger device.

**Comment by gjeee** [comment]
i can confirm this bug

**Comment by ajbmachon** [comment]
I tested logging in agian yesterday,  it works again without me taking any
action with the wallet in the meantime.

**Comment by MiKeF05** [comment]
@gjeee Can you try to update Firefly to the latest release 1.3.3?

**Comment by gjeee** [comment]
i updated, but i still have this error

**Comment by MiKeF05** [comment]
Can you try to create a new profile and recover your wallet with your 24 words or stronghold + password? If you use a ledger device then with your ledger.

**Comment by MiKeF05** [comment]
This should be fixed with the latest release.

**Comment by gjeee** [comment]
> This should be fixed with the latest release.

I tried and indeed the bug is gone! Thanks.
