### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by JOiota** [iotaledger/firefly#2309]
### Issue description

App Version: 1.3.3

platform: win32
platformVersion: 10.0.22000
platformArchitecture: x64
cpuCount: 8
totalMem: 7103.6 MB
freeMem: 2819.0 MB

Error Type: Callback Error latestAddress

TypeError: Cannot read property 'balance' of undefined
    at file:///C:/Program%20Files/Firefly/resources/app.asar/public/build/index.js:2:3060474
    at Array.map (<anonymous>)
    at file:///C:/Program%20Files/Firefly/resources/app.asar/public/build/index.js:2:3060411
    at Array.forEach (<anonymous>)
    at file:///C:/Program%20Files/Firefly/resources/app.asar/public/build/index.js:2:3060370
    at Array.forEach (<anonymous>)
    at file:///C:/Program%20Files/Firefly/resources/app.asar/public/build/index.js:2:3060339
    at file:///C:/Program%20Files/Firefly/resources/app.asar/public/build/index.js:2:3060502
    at m (file:///C:/Program%20Files/Firefly/resources/app.asar/public/build/index.js:2:2027894)
    at Array.<anonymous> (file:///C:/Program%20Files/Firefly/resources/app.asar/public/build/index.js:2:2027973)
    at i (file:///C:/Program%20Files/Firefly/resources/app.asar/public/build/index.js:2:2027509)
    at Object.update (file:///C:/Program%20Files/Firefly/resources/app.asar/public/build/index.js:2:2027565)
    at file:///C:/Program%20Files/Firefly/resources/app.asar/public/build/index.js:2:3062568
    at onSuccess (file:///C:/Program%20Files/Firefly/resources/app.asar/public/build/index.js:2:2114063)
    at Function.t.<computed>.<computed> (file:///C:/Program%20Files/Firefly/resources/app.asar/public/build/index.js:2:2108132)

### Expected behaviour

Can`t login with ledger anymore.

### Actual behaviour

Can`t login with ledger anymore.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

If I want to login with ledger I reproduce the issue.

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JOiota** [comment]
Made a new wallet... and all is fine...
