### ISSUE TITLE
[Bug]: Unable to open up wallet after latest trasnaction 

### ISSUE THREAD

**Issue by SolGnarly** [iotaledger/firefly#2326]
### Issue description

I sent a small transaction to an existing wallet and as soon as it was received a error window popped up and now I am unable to log in and see balances. After PIN entry the error window appears. 

I synced the wallet on a separate PC and as soon as that transaction loads the same error appears 

I can access other wallets fine and can access this wallet up until I run balance finder and locate the missing funds.
Then it throws the same error and I am locked again 

### Expected behaviour

Log in and see balances 

### Actual behaviour

After Pin Firefly freezes and gives error pop up 

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. open firefly
2. select the problem wallet
3. enter pin 
4. Get error / firefly freeze 

### Diagnostics

```shell
Firefly v1.3.3
Platform: win32
Platform Version: 6.1.7600
Platform Architecture: x64
CPU Count: 20
Total Memory: 65390.9 MB
Free Memory: 56722.4 MB
```

### Errors

```shell
App Version: 1.3.3

platform: win32
platformVersion: 6.1.7600
platformArchitecture: x64
cpuCount: 20
totalMem: 65390.9 MB
freeMem: 57016.4 MB

Error Type: Callback Error latestAddress

TypeError: Cannot read property 'balance' of undefined
    at file:///C:/Program%20Files/Firefly/resources/app.asar/public/build/index.js:2:3060474
    at Array.map (<anonymous>)
    at file:///C:/Program%20Files/Firefly/resources/app.asar/public/build/index.js:2:3060411
    at Array.forEach (<anonymous>)
    at file:///C:/Program%20Files/Firefly/resources/app.asar/public/build/index.js:2:3060370
    at Array.forEach (<anonymous>)
    at file:///C:/Program%20Files/Firefly/resources/app.asar/public/build/index.js:2:3060339
    at file:///C:/Program%20Files/Firefly/resources/app.asar/public/build/index.js:2:3060502
    at m (file:///C:/Program%20Files/Firefly/resources/app.asar/public/build/index.js:2:2027894)
    at Array.<anonymous> (file:///C:/Program%20Files/Firefly/resources/app.asar/public/build/index.js:2:2027973)
    at i (file:///C:/Program%20Files/Firefly/resources/app.asar/public/build/index.js:2:2027509)
    at Object.update (file:///C:/Program%20Files/Firefly/resources/app.asar/public/build/index.js:2:2027565)
    at file:///C:/Program%20Files/Firefly/resources/app.asar/public/build/index.js:2:3062568
    at onSuccess (file:///C:/Program%20Files/Firefly/resources/app.asar/public/build/index.js:2:2114063)
    at Function.t.<computed>.<computed> (file:///C:/Program%20Files/Firefly/resources/app.asar/public/build/index.js:2:2108132)
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dervoegli** [comment]
I have the same problem, but there was no error window. 
I sent 2 transactions, first was OK, after second there was no status actualisation. After restarting the program I am unable to log in and see balances, after PIN entry nothing happens anymore, can see only the firefly. Diagnostics and error logs impossible.

**Comment by adamkundrat** [comment]
I'm experiencing same issue. I've had to reset the wallet numerous times and recover from backup. Even after that it keeps happening again and again. My wallet is eventually stuck.

```
Error Type: Callback Error latestAddress

TypeError: Cannot read property 'balance' of undefined
    at file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:3060000
    at Array.map (<anonymous>)
    at file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:3059937
    at Array.forEach (<anonymous>)
    at file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:3059896
    at Array.forEach (<anonymous>)
    at file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:3059865
    at file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:3060028
    at m (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2027894)
    at Array.<anonymous> (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2027973)
    at i (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2027509)
    at Object.update (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2027565)
    at file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:3062094
    at onSuccess (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2114063)
    at Function.t.<computed>.<computed> (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2108132)
    ```

**Comment by MiKeF05** [comment]
Hello, I´m going to close this issue because it is a duplicate to #2198. Please feel free to comment at issue #2198.
