### ISSUE TITLE
[Bug]: Issue creating new wallet

### ISSUE THREAD

**Issue by Cool-Dr-T** [iotaledger/firefly#2504]
### Issue description

Got the following error message when creating a wallet
App Version: 1.3.3

platform: linux
platformVersion: 5.13.0-30-generic
platformArchitecture: x64
cpuCount: 8
totalMem: 15823.2 MB
freeMem: 7219.2 MB

Error Type: Callback Error syncAccounts

TypeError: Cannot read property 'depositAddress' of undefined
    at file:///tmp/.mount_fireflEecxgi/resources/app.asar/public/build/index.js:2:2112661
    at Array.map (<anonymous>)
    at Bs (file:///tmp/.mount_fireflEecxgi/resources/app.asar/public/build/index.js:2:2112600)
    at onSuccess (file:///tmp/.mount_fireflEecxgi/resources/app.asar/public/build/index.js:2:2110251)
    at Function.t.<computed>.<computed> (file:///tmp/.mount_fireflEecxgi/resources/app.asar/public/build/index.js:2:2108132)

### Expected behaviour

new wallet should have been created.

### Actual behaviour

Error message was displayed then wallet appeared.

### Can the issue reliably be reproduced?

No

### Errors

```shell
App Version: 1.3.3

platform: linux
platformVersion: 5.13.0-30-generic
platformArchitecture: x64
cpuCount: 8
totalMem: 15823.2 MB
freeMem: 7219.2 MB

Error Type: Callback Error syncAccounts

TypeError: Cannot read property 'depositAddress' of undefined
    at file:///tmp/.mount_fireflEecxgi/resources/app.asar/public/build/index.js:2:2112661
    at Array.map (<anonymous>)
    at Bs (file:///tmp/.mount_fireflEecxgi/resources/app.asar/public/build/index.js:2:2112600)
    at onSuccess (file:///tmp/.mount_fireflEecxgi/resources/app.asar/public/build/index.js:2:2110251)
    at Function.t.<computed>.<computed> (file:///tmp/.mount_fireflEecxgi/resources/app.asar/public/build/index.js:2:2108132)
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
Hi, is this still an issue in the latest version?

**Comment by Cool-Dr-T** [comment]
no, i thought this was closed.On 20 Sep 2023, at 14:29, Begoña Álvarez de la Cruz ***@***.***> wrote:Hi, is this still an issue in the latest version?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
