### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by DanieKrie** [iotaledger/firefly#2749]
### Platform

Desktop

### Version

1.3.3

### Description

Wanted to trasfer iotas from my wallet to an adress. Got error message and firefly crashed. Can´t log in anymore.

Whenever I try to login, firefly crashes.

### Expected behaviour

Expected transfer to happen and firefly to open again

### Actual behaviour

Can´t open firefly anymore. After entering 6 Digit Number error message shows again and then firefly keeps showing activity indicator, but does not open

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

open firefly
enter 6 digit code
Error message appears

### Operating System

Mac

### Diagnostics

```shell
App Version: 1.3.3

platform: macOS
platformVersion: 12.3
platformArchitecture: x64
cpuCount: 8
totalMem: 16384.0 MB
freeMem: 36.6 MB

Error Type: Callback Error onNewTransaction

TypeError: Cannot read property 'balance' of undefined
    at file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:3060000
    at Array.map (<anonymous>)
    at file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:3059937
    at Array.forEach (<anonymous>)
    at file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:3059896
    at Array.forEach (<anonymous>)
    at file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:3059865
    at file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:3060028
    at m (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2027894)
    at Array.<anonymous> (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2027973)
    at i (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2027509)
    at Object.update (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2027565)
    at Fs (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2111243)
    at onSuccess (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:3062791)
    at Function.t.<computed>.<computed> (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2108132)
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

Infinite loading symbol

### Error Messages

Unfortunately an error has occured in Firefly.

### Error Logs

```shell
App Version: 1.3.3

platform: macOS
platformVersion: 12.3
platformArchitecture: x64
cpuCount: 8
totalMem: 16384.0 MB
freeMem: 17.3 MB

Error Type: Callback Error latestAddress

TypeError: Cannot read property 'balance' of undefined
    at file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:3060000
    at Array.map (<anonymous>)
    at file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:3059937
    at Array.forEach (<anonymous>)
    at file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:3059896
    at Array.forEach (<anonymous>)
    at file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:3059865
    at file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:3060028
    at m (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2027894)
    at Array.<anonymous> (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2027973)
    at i (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2027509)
    at Object.update (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2027565)
    at file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:3062094
    at onSuccess (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2114063)
    at Function.t.<computed>.<computed> (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2108132)
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jimmyjohnson777** [comment]
I'm having this same issue

**Comment by nicole-obrien** [comment]
Fixed in https://github.com/iotaledger/firefly/releases/tag/desktop-1.4.2
