### ISSUE TITLE
[Bug report]:  Can't migrate from Trinity to Firefly

### ISSUE THREAD

**Issue by Flojoke** [iotaledger/firefly#2783]
### Platform

Desktop

### Version

1.4.1

### Description

When opening IOTA legacy app on ledger and start searching. I get stuck here:

Error in Firefly:

App Version: 1.4.1

platform: win32
platformVersion: 10.0.19044
platformArchitecture: x64
cpuCount: 16
totalMem: 32693.9 MB
freeMem: 27366.2 MB

Error Type: Callback Error getLedgerDeviceStatus

TypeError: Cannot read property 'selectSeed' of undefined
    at o (file:///C:/Users/flojoke/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2883256)
    at s (file:///C:/Users/flojoke/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2232324)
    at onSuccess (file:///C:/Users/flojoke/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2232138)
    at e.<computed>.<computed> (file:///C:/Users/flojoke/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2204288)
    at Function.<anonymous> (file:///C:/Users/flojoke/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2197511)

### Expected behaviour

Migrate from Trinity to Firefly

### Actual behaviour

When opening IOTA legacy app on ledger and start searching. I get stuck with an error.
The IOTA app on ledger seems to work. But when it comes to the IOTA Legacy app there is something wrong

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Follow the migration process with a ledger device

### Operating System

Windows

### Diagnostics

```shell
App Version: 1.4.1

platform: win32
platformVersion: 10.0.19044
platformArchitecture: x64
cpuCount: 16
totalMem: 32693.9 MB
freeMem: 27366.2 MB

Error Type: Callback Error getLedgerDeviceStatus

TypeError: Cannot read property 'selectSeed' of undefined
    at o (file:///C:/Users/flojoke/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2883256)
    at s (file:///C:/Users/flojoke/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2232324)
    at onSuccess (file:///C:/Users/flojoke/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2232138)
    at e.<computed>.<computed> (file:///C:/Users/flojoke/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2204288)
    at Function.<anonymous> (file:///C:/Users/flojoke/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2197511)
```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Crash Status

None of the above

### Error Messages

App Version: 1.4.1

platform: win32
platformVersion: 10.0.19044
platformArchitecture: x64
cpuCount: 16
totalMem: 32693.9 MB
freeMem: 27366.2 MB

Error Type: Callback Error getLedgerDeviceStatus

TypeError: Cannot read property 'selectSeed' of undefined
    at o (file:///C:/Users/flojoke/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2883256)
    at s (file:///C:/Users/flojoke/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2232324)
    at onSuccess (file:///C:/Users/flojoke/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2232138)
    at e.<computed>.<computed> (file:///C:/Users/flojoke/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2204288)
    at Function.<anonymous> (file:///C:/Users/flojoke/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2197511)

### Error Logs

```shell
App Version: 1.4.1

platform: win32
platformVersion: 10.0.19044
platformArchitecture: x64
cpuCount: 16
totalMem: 32693.9 MB
freeMem: 27366.2 MB

Error Type: Callback Error getLedgerDeviceStatus

TypeError: Cannot read property 'selectSeed' of undefined
    at o (file:///C:/Users/flojoke/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2883256)
    at s (file:///C:/Users/flojoke/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2232324)
    at onSuccess (file:///C:/Users/flojoke/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2232138)
    at e.<computed>.<computed> (file:///C:/Users/flojoke/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2204288)
    at Function.<anonymous> (file:///C:/Users/flojoke/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2197511)
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ninware** [comment]
Hello, i have the same problem on Mac OS Monterey 12.2.1
This happens after setting Ledger Account Index.

App Version: 1.4.1

platform: macOS
platformVersion: 12.2.1
platformArchitecture: x64
cpuCount: 4
totalMem: 8192.0 MB
freeMem: 119.5 MB

Error Type: Callback Error getLedgerDeviceStatus

TypeError: Cannot read property 'selectSeed' of undefined
    at o (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2882812)
    at s (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2232324)
    at onSuccess (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2232138)
    at e.<computed>.<computed> (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2204288)
    at Function.<anonymous> (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2197511)

**Comment by cvarley100** [comment]
A fix will be available in the next release.

**Comment by Flojoke** [comment]
Hi all,
I checked the ticket. It looks like the fix is only for MacOs. I have the problem on windows os. I hope the fix is also working for there.

**Comment by Flojoke** [comment]
Thanks a lot

**Comment by LionelCutz** [comment]
I tried the 1.4.2 release and it still doesn't work. Any ideas? Thanks a lot!




App Version: 1.4.2

platform: macOS
platformVersion: 10.13.6
platformArchitecture: x64
cpuCount: 8
totalMem: 10240.0 MB
freeMem: 4147.1 MB

Error Type: Callback Error getLedgerDeviceStatus

TypeError: Cannot read property 'selectSeed' of undefined
    at o (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2882882)
    at s (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2232324)
    at onSuccess (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2232138)
    at e.<computed>.<computed> (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2204288)
    at Function.<anonymous> (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2197511)
