### ISSUE TITLE
[Task]: fix mobile system notifications

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#4304]
### Task description

im getting this error in Android 12
```
wallet.ts:147 Callback Error onNewTransaction ReferenceError: Notification is not defined
    at Object.notify (notificationManager.ts:10:1)
    at showNotification (notifications.ts:34:1)
    at showSystemNotification (notifications.ts:17:1)
    at onSuccess (walletApiListeners.ts:85:1)
    at args.<computed>.<computed> (wallet.ts:157:1)
    at walletApi.ts:192:1
    at walletPluginApi.ts:101:1
    at Array.forEach (<anonymous>)
    at Object.callback (walletPluginApi.ts:101:1)
    at cap.fromNative ((index):418:44)
    at <anonymous>:1:18
```
it comes from `packages/mobile/capacitor/lib/notificationManager.ts`
`const notification = new Notification `<<-- `Notification is not defined`

### Requirements

mobile system notifications working

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by paul-boegelsack** [comment]
iOS is the same
