### ISSUE TITLE
[Task]: Fix mainnet profile crash

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#7043]
### Task description

At the moment, we are not able to create a mainnet profile, it crashes with 
```
iscp-chain.class.ts:29 Error: Can't autodetect provider for "/v1/chains//evm"
    at c.setProvider (web3.min.js:2:1)
    at new e (web3.min.js:2:1)
    at Object.packageInit (web3.min.js:2:1)
    at new d (web3.min.js:2:1)
    at new IscpChain (iscp-chain.class.ts:26:1)
    at stardust-network.class.ts:27:1
    at Array.map (<anonymous>)
    at StardustNetwork.constructChains (stardust-network.class.ts:24:1)
    at new StardustNetwork (stardust-network.class.ts:20:1)
    at network.store.ts:10:1
```
```
index.js:31 Error: Failed to construct ISCP Chain!
    at new IscpChain (iscp-chain.class.ts:30:1)
    at stardust-network.class.ts:27:1
    at Array.map (<anonymous>)
    at StardustNetwork.constructChains (stardust-network.class.ts:24:1)
    at new StardustNetwork (stardust-network.class.ts:20:1)
    at network.store.ts:10:1
    at sync (index.mjs:77:1)
    at index.mjs:95:1
    at Object.subscribe (index.mjs:48:1)
    at subscribe (index.mjs:57:1)
```

### Requirements

Fix crash

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
Fixed by https://github.com/iotaledger/firefly/pull/7044
