### ISSUE TITLE
[Task]: I have a problem after updating (Firefly 2.0.1) - days, linux version

### ISSUE THREAD

**Issue by banigood** [iotaledger/firefly#7561]
### Task description

unable to launch the application, an error appears:
Linux ubuntu Version: ubuntu 22.04.3 LTS  64 bits
Firefly: Found version 2.0.1 (url: firefly-iota-desktop-2.0.1.AppImage)

Bug:  Error
[714457:1009/064638.850819:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[714457:1009/064641.181171:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
Error occurred in handler for 'update-theme': TypeError: Error processing argument at index 0, conversion failure from undefined
    at /tmp/.mount_fireflbQfscU/resources/app.asar/public/build/main.js:2:444038
    at node:electron/js2c/browser_init:2:97909
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81422)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:489:12)
    at n.emit (/tmp/.mount_fireflbQfscU/resources/app.asar/public/build/main.js:2:38610)
Error occurred in handler for 'update-theme': TypeError: Error processing argument at index 0, conversion failure from undefined
    at /tmp/.mount_fireflbQfscU/resources/app.asar/public/build/main.js:2:444038
    at node:electron/js2c/browser_init:2:97909
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81422)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:489:12)
    at n.emit (/tmp/.mount_fireflbQfscU/resources/app.asar/public/build/main.js:2:38610)
Error occurred in handler for 'update-theme': TypeError: Error processing argument at index 0, conversion failure from undefined
    at /tmp/.mount_fireflbQfscU/resources/app.asar/public/build/main.js:2:444038
    at node:electron/js2c/browser_init:2:97909
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81422)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:489:12)
    at n.emit (/tmp/.mount_fireflbQfscU/resources/app.asar/public/build/main.js:2:38610)
Error occurred in handler for 'update-theme': TypeError: Error processing argument at index 0, conversion failure from undefined
    at /tmp/.mount_fireflbQfscU/resources/app.asar/public/build/main.js:2:444038
    at node:electron/js2c/browser_init:2:97909
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81422)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:489:12)
    at n.emit (/tmp/.mount_fireflbQfscU/resources/app.asar/public/build/main.js:2:38610)
[714457:1009/064644.645921:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!

### Requirements

tell me what to do or fix the bug, thank you for your feedback

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by banigood** [comment]
the latest version firefly  2.0.2 solves the problem
