### ISSUE TITLE
Firefly 1.3.3[Bug report]: 

### ISSUE THREAD

**Issue by Mazak23** [iotaledger/firefly#8481]
### Version

1.3.3

### Description

App Version: 1.3.3

platform: linux
platformVersion: 6.5.0-28-generic
platformArchitecture: x64
cpuCount: 8
totalMem: 15731.5 MB
freeMem: 282.0 MB

Error Type: Callback Error createAccount

TypeError: Cannot read property 'usd' of null
    at Us (file:///tmp/.mount_firefleAxpOg/resources/app.asar/public/build/index.js:2:2114550)
    at onSuccess (file:///tmp/.mount_firefleAxpOg/resources/app.asar/public/build/index.js:2:2109486)
    at Function.t.<computed>.<computed> (file:///tmp/.mount_firefleAxpOg/resources/app.asar/public/build/index.js:2:2108132)

### Expected behaviour

Recover wallet

### Actual behaviour

crash

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

After putting new password it crash

### Operating System

Linux

### Diagnostics

```shell
App Version: 1.3.3

platform: linux
platformVersion: 6.5.0-28-generic
platformArchitecture: x64
cpuCount: 8
totalMem: 15731.5 MB
freeMem: 282.0 MB

Error Type: Callback Error createAccount

TypeError: Cannot read property 'usd' of null
    at Us (file:///tmp/.mount_firefleAxpOg/resources/app.asar/public/build/index.js:2:2114550)
    at onSuccess (file:///tmp/.mount_firefleAxpOg/resources/app.asar/public/build/index.js:2:2109486)
    at Function.t.<computed>.<computed> (file:///tmp/.mount_firefleAxpOg/resources/app.asar/public/build/index.js:2:2108132)
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Error Logs

```shell
App Version: 1.3.3

platform: linux
platformVersion: 6.5.0-28-generic
platformArchitecture: x64
cpuCount: 8
totalMem: 15731.5 MB
freeMem: 282.0 MB

Error Type: Callback Error createAccount

TypeError: Cannot read property 'usd' of null
    at Us (file:///tmp/.mount_firefleAxpOg/resources/app.asar/public/build/index.js:2:2114550)
    at onSuccess (file:///tmp/.mount_firefleAxpOg/resources/app.asar/public/build/index.js:2:2109486)
    at Function.t.<computed>.<computed> (file:///tmp/.mount_firefleAxpOg/resources/app.asar/public/build/index.js:2:2108132)
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
You should update your wallet to the newest version, 1.3.3 is not compatible with the network upgrade that happened in Octobot 2023. The latest version we have at the time of writing this comment is `V2.0.9`. You can find the latest version in the official website https://firefly.iota.org/
