### ISSUE TITLE
[Bug report]: I cannot recover/verify my account

### ISSUE THREAD

**Issue by melissa-pereira-deel** [iotaledger/firefly#8540]
### Version

1.7.2

### Description

App Version: 1.7.2

platform: macOS
platformVersion: 13.2.1
platformArchitecture: x64
cpuCount: 8
totalMem: 16384.0 MB
freeMem: 78.2 MB

Error Type: Callback Error createAccount

TypeError: Cannot read property 'usd' of null
    at He (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:1448616)
    at onSuccess (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:1440124)
    at e.<computed>.<computed> (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:1438028)
    at Function.<anonymous> (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:1435210)

### Expected behaviour

I should be able to recover my account, define new password and pin 

### Actual behaviour

I tried to recover my account using the recovery phrase, the initial steps went well, then the bug happened after I tried to verify my recovery phrase 

### Can the issue reliably be reproduced?

No

### Operating System

Mac

### Diagnostics

```shell
Mac M2
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

None of the above

### Error Messages

App Version: 1.7.2

platform: macOS
platformVersion: 13.2.1
platformArchitecture: x64
cpuCount: 8
totalMem: 16384.0 MB
freeMem: 78.2 MB

Error Type: Callback Error createAccount

TypeError: Cannot read property 'usd' of null
    at He (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:1448616)
    at onSuccess (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:1440124)
    at e.<computed>.<computed> (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:1438028)
    at Function.<anonymous> (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:1435210)

### Error Logs

```shell
App Version: 1.7.2

platform: macOS
platformVersion: 13.2.1
platformArchitecture: x64
cpuCount: 8
totalMem: 16384.0 MB
freeMem: 78.2 MB

Error Type: Callback Error createAccount

TypeError: Cannot read property 'usd' of null
    at He (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:1448616)
    at onSuccess (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:1440124)
    at e.<computed>.<computed> (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:1438028)
    at Function.<anonymous> (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:1435210)
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
You are running a very old version of Firefly. You should upgrade to latest version since the one you are using is not compatible with the latest protocol version, as of today the latest version is `V2.0.11`
